version: '3.8'
services:
  battleship-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://battleship-db:5432/battleship
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      battleship-db:
        condition: service_healthy
    networks:
      - battleship-network

  battleship-frontend:
    build:
      context: ../battlershipF
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - battleship-backend
    networks:
      - battleship-network

  battleship-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: battleship
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s
    networks:
      - battleship-network

volumes:
  postgres-data:

networks:
  battleship-network:
    driver: bridge